[package]
name = "peer-quality-metrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
systemstat = "0.1.10"
sysinfo = "0.23.5"
more-asserts = "0.2.2"